version: '3'
services:
  nodejs-app:
    image: jessehoch/pacman-nodejs-app:latest
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  mongo:
    image: mongo
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    volumes:
      - mongo-db:/mnt/data/db
volumes:
  mongo-db:
    driver: local