apiVersion: traefik.containo.us/v1alpha1
kind: TraefikConfiguration
metadata:
  name: traefik-config
spec:
  providers:
    kubernetesCRD: {}
    aws:
      accessKey:
        name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-route53-credentials
            key: AWS_ACCESS_KEY_ID
      secretKey:
        name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-route53-credentials
            key: AWS_SECRET_ACCESS_KEY
      region: "us-east-1" # Specify your desired AWS region
  entryPoints:
    web:
      address: ":80"
    websecure:
      address: ":443"
  api:
    insecure: true
  accessLog: {}
  log:
    level: WARN
  ping: {}
  metrics: {}
  deployment:
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
