
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-cluster-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.10-192.168.1.150
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-cluster-pool
  # Include nodeSelectors if needed, with appropriate labels.
  # nodeSelectors:
  # - matchLabels:
  #     kubernetes.io/hostname: "<desired-hostname>"

